# Generated by Django 5.2.17 on 2026-08-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mastery_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "accuracy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                ("completed_games_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_date", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_masteries",
                        to="academics.concept",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Concept Masteries",
                "unique_together": {("student", "concept")},
            },
        ),
    ]
