# Generated by Django 5.2.16 on 2026-08-29 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_class_options_chapter_description_and_more"),
        ("accounts", "0004_remove_studentprofile_membership_expiry_and_more"),
        ("progress", "0002_quizattempt_lessonprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTopicProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_unlocked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this topic is accessible to the student",
                    ),
                ),
                ("learn_completed", models.BooleanField(default=False)),
                ("learn_completed_at", models.DateTimeField(blank=True, null=True)),
                ("game_unlocked", models.BooleanField(default=False)),
                ("game_completed", models.BooleanField(default=False)),
                ("game_score", models.PositiveIntegerField(default=0)),
                ("game_completed_at", models.DateTimeField(blank=True, null=True)),
                ("quiz_unlocked", models.BooleanField(default=False)),
                ("quiz_completed", models.BooleanField(default=False)),
                ("quiz_score", models.PositiveIntegerField(default=0)),
                ("quiz_total_marks", models.PositiveIntegerField(default=0)),
                ("quiz_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accuracy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("hints_used", models.PositiveIntegerField(default=0)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("coins_earned", models.PositiveIntegerField(default=0)),
                (
                    "mastery_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_mastered", models.BooleanField(default=False)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_topic_progresses",
                        to="academics.concept",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_progresses",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Topic Progress",
                "verbose_name_plural": "Student Topic Progresses",
                "ordering": ["concept__order"],
                "unique_together": {("student", "concept")},
            },
        ),
    ]
