# Generated by Django 5.2.16 on 2026-09-10 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_alter_class_options_chapter_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="e.g. 'Create Game', 'Upload ZIP', 'Modify Topic'",
                        max_length=100,
                    ),
                ),
                ("target_model", models.CharField(max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicUnlockRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learn_enabled", models.BooleanField(default=True)),
                ("game_enabled", models.BooleanField(default=True)),
                ("quiz_enabled", models.BooleanField(default=True)),
                ("require_learn_for_game", models.BooleanField(default=True)),
                ("require_game_for_quiz", models.BooleanField(default=True)),
                ("unlock_next_topic_on_quiz", models.BooleanField(default=True)),
                ("max_game_attempts", models.PositiveIntegerField(default=5)),
                ("hints_allowed", models.PositiveIntegerField(default=3)),
                ("custom_xp_bonus", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlock_rule",
                        to="academics.concept",
                    ),
                ),
            ],
        ),
    ]
