# Generated by Django 5.2.17 on 2026-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
