# Generated by Django 5.2.17 on 2026-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="membership_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="membership_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
