# Generated by Django 5.2.16 on 2026-08-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studentprofile_membership_expiry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="membership_expiry",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="membership_start",
        ),
    ]
