# Generated by Django 5.2.16 on 2026-09-10 17:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Level 1 — Free Membership"),
                            (2, "Level 2 — Standard Membership"),
                            (3, "Level 3 — Premium Membership"),
                        ]
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(db_index=True, max_length=36, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("PENDING", "Pending"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField()),
                (
                    "activated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("is_free_tier", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "membership_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Level 1 — Free Membership"),
                            (2, "Level 2 — Standard Membership"),
                            (3, "Level 3 — Premium Membership"),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("duration_days", models.PositiveIntegerField(default=365)),
                ("badge_text", models.CharField(blank=True, max_length=60)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of feature strings for display",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membership Plan",
                "verbose_name_plural": "Membership Plans",
                "ordering": ["membership_level"],
            },
        ),
    ]
