# Generated by Django 5.2.16 on 2026-09-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_remove_studentprofile_membership_expiry_and_more"),
        ("memberships", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_membership",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="accounts.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="memberships.membershipplan",
            ),
        ),
    ]
