# Generated by Django 5.2.16 on 2026-08-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_studentprofile_membership_expiry_and_more"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🏆", max_length=50)),
                ("xp_reward", models.PositiveIntegerField(default=50)),
                ("coin_reward", models.PositiveIntegerField(default=25)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("xp_total", "Total XP Earned"),
                            ("streak_days", "Streak Days"),
                            ("quizzes_passed", "Quizzes Passed"),
                            ("games_completed", "Games Completed"),
                            ("lessons_completed", "Lessons Completed"),
                            ("perfect_quiz", "Perfect Quiz Score"),
                            ("first_game", "First Game Played"),
                            ("first_lesson", "First Lesson Completed"),
                            ("first_quiz", "First Quiz Passed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("condition_value", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["condition_type", "condition_value"],
            },
        ),
        migrations.AlterField(
            model_name="dailymission",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("games_count", "Games Count"),
                    ("concepts_count", "Concepts Count"),
                    ("questions_solved", "Questions Solved"),
                    ("xp_earned", "XP Earned"),
                    ("streak_days", "Streak Days"),
                    ("lessons_completed", "Lessons Completed"),
                    ("quizzes_passed", "Quizzes Passed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="StudentAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="rewards.achievement",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Achievements",
                "unique_together": {("student", "achievement")},
            },
        ),
    ]
