# Generated by Django 5.2.16 on 2026-08-29 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_studentprofile_membership_expiry_and_more"),
        ("games", "0002_question_explanation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamelevel",
            options={"ordering": ["level_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="gamelevel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="hint",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="game",
            name="coin_reward",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="game",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="estimated_time",
            field=models.PositiveIntegerField(
                default=15, help_text="Estimated play time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                default="house_builder",
                help_text="Engine identifier: house_builder, shopping, fractions, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="game",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="game",
            name="xp_reward",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="level_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="points",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="time_limit",
            field=models.PositiveIntegerField(
                default=60, help_text="Time limit in seconds"
            ),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="title",
            field=models.CharField(default="Level 1", max_length=255),
        ),
        migrations.AddField(
            model_name="gamelevel",
            name="unlock_requirement",
            field=models.CharField(
                blank=True, default="Complete previous level", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="current_level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="session_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.question",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.questionoption",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_attempts",
                to="games.gamesession",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="game",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.gametemplate",
            ),
        ),
        migrations.AlterField(
            model_name="gamelevel",
            name="coin_reward",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="gamelevel",
            name="difficulty",
            field=models.CharField(default="easy", max_length=20),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="difficulty",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AlterField(
            model_name="hint",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_hints",
                to="games.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="game_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_questions",
                to="games.gamelevel",
            ),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_options",
                to="games.question",
            ),
        ),
        migrations.CreateModel(
            name="GameContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("read_number", "Read Number"),
                            ("build_number", "Build Number"),
                            ("place_value", "Place Value"),
                            ("compare_order", "Compare & Order"),
                            ("budget_verification", "Budget Verification"),
                            ("mcq", "Multiple Choice"),
                        ],
                        default="read_number",
                        max_length=50,
                    ),
                ),
                ("question", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("correct_answer", models.JSONField(blank=True, default=dict)),
                ("hint", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("points", models.PositiveIntegerField(default=100)),
                ("difficulty", models.CharField(default="easy", max_length=20)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="games.game",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="games.gamelevel",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="GameAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_answer", models.JSONField(blank=True, default=dict)),
                ("is_correct", models.BooleanField(default=False)),
                ("time_taken", models.PositiveIntegerField(default=0)),
                ("hints_used", models.PositiveIntegerField(default=0)),
                ("points_earned", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.gamelevel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_attempts",
                        to="games.gamesession",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.gamecontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("text", models.TextField()),
                ("cost_points", models.PositiveIntegerField(default=10)),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="games.gamecontent",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="games.gamelevel",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GameReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(default="game_complete", max_length=50),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("xp_reward", models.PositiveIntegerField(default=20)),
                ("coin_reward", models.PositiveIntegerField(default=5)),
                (
                    "badge_icon",
                    models.CharField(blank=True, default="🏆", max_length=50),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="games.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_level", models.PositiveIntegerField(default=1)),
                ("highest_level", models.PositiveIntegerField(default=1)),
                ("best_score", models.PositiveIntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("last_played_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progresses",
                        to="games.game",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_progresses",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "game")},
            },
        ),
    ]
