# Generated by Django 5.2.16 on 2026-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_gamelevel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path within games/ folder, e.g. class_5/mathematics/chapter_01_large_numbers/topic_01_reading_writing_numbers/number_builder",
                max_length=500,
            ),
        ),
    ]
