# Generated by Django 5.2.17 on 2026-08-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_number", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("class_label", models.CharField(max_length=50)),
                ("stage", models.CharField(max_length=100)),
                ("age_group", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("middle", "Middle"),
                            ("senior", "Senior"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("subtitle", models.CharField(max_length=255)),
                ("olympiad_code", models.CharField(max_length=100)),
                (
                    "icon_type",
                    models.CharField(
                        choices=[
                            ("math", "math"),
                            ("science", "science"),
                            ("english", "english"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color_theme", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_modules", models.PositiveIntegerField(default=0)),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="academics.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("student_class", "subject")},
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "class_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="academics.classsubject",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("class_subject", "order")},
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("real_world_example", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="academics.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("chapter", "order")},
            },
        ),
    ]
