# Generated by Django 5.2.16 on 2026-08-28 07:30 (manually extended)

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_class_slugs(apps, schema_editor):
    """Auto-generate slugs for all existing Class records."""
    Class = apps.get_model("academics", "Class")
    for cls in Class.objects.all():
        cls.slug = slugify(cls.class_label) or f"class-{cls.grade_number}"
        cls.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["grade_number"], "verbose_name_plural": "Classes"},
        ),
        migrations.AddField(
            model_name="chapter",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="class",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="class",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        # Step 1: add slug as non-unique with blank=True so existing rows get ''
        migrations.AddField(
            model_name="class",
            name="slug",
            field=models.SlugField(blank=True, default=""),
            preserve_default=False,
        ),
        # Step 2: populate unique slugs for existing rows
        migrations.RunPython(populate_class_slugs, migrations.RunPython.noop),
        # Step 3: now add the unique constraint
        migrations.AlterField(
            model_name="class",
            name="slug",
            field=models.SlugField(unique=True, blank=True),
        ),
        migrations.AddField(
            model_name="class",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="concept",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="estimated_time",
            field=models.PositiveIntegerField(
                default=15, help_text="Estimated time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="concept",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=10, help_text="Time limit in minutes"
                    ),
                ),
                ("passing_percentage", models.PositiveIntegerField(default=60)),
                ("xp_reward", models.PositiveIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="academics.concept",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Shown after answering"),
                ),
                ("marks", models.PositiveIntegerField(default=1)),
                ("display_order", models.PositiveIntegerField(default=1)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="academics.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="academics.quizquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=50)),
                ("coin_reward", models.PositiveIntegerField(default=25)),
                ("date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_challenges",
                        to="academics.class",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("student_class", "date")},
            },
        ),
    ]
