# Generated by Django 5.2.17 on 2026-08-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("BADGE_UNLOCKED", "Badge Unlocked"),
                            ("ACHIEVEMENT_UNLOCKED", "Achievement Unlocked"),
                            ("MISSION_COMPLETED", "Mission Completed"),
                            ("PROGRESS_MILESTONE", "Progress Milestone"),
                            ("STREAK_ALERT", "Streak Alert"),
                            ("NEW_CHALLENGE", "New Challenge"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
